package towers;

import java.io.Serializable;

/*
 * Helix Industries:{
 * Daniel S. Luces
 * Will Clement
 * Brandon Brown
 * Gabriel Basadre
 * 
 */

public enum TowerID implements Serializable
{
	BLANK,BULBASAUR,IVYSAUR,VENUSAUR,CHARMANDER,CHARMELEON,CHARIZARD,SQUIRTLE,WARTORTLE,BLASTOISE,
	PIKACHU,RAICHU,DIGLETT,DUGTRIO,JIGGLYPUFF,WIGGLYTUFF,CLEFAIRY,CLEFABLE,MEOWTH,PERSIAN,
	ODDISH,GLOOM,VILEPLUME,PIDGEY,PIDGEOTTO,PIDGEOT,ABRA,KADABRA,ALAKAZAM,SCYTHER,
	MAGNEMITE,MAGNETON,EKANS,ARBOK,GROWLITHE,ARCANINE,GRIMER,MUK,DODUO,DODRIO,
	POLYWAG,POLYWHIRL,POLIWRATH,MACHOP,MACHOKE,MACHAMP,GEODUDE,GRAVELER,GOLEM,HITMONLEE,
	GHASTLY,HAUNTER,GENGAR,EEVEE,VAPOREON,JOLTEON,FLAREON, ONIX,DROWZEE,HYPNO;
	
}
