package Mob;

/*
 * Helix Industries:{
 * Daniel S. Luces
 * Will Clement
 * Brandon Brown
 * Gabriel Basadre
 * 
 */

public enum MobID {
	AERODACTYL, ALAKAZAM, ARBOK, ARCANINE, ARTICUNO, BELLSPROUT, BLASTOISE, CATERPIE, CHARIZARD,
	CLOYSTER, DEWGONG, DIGLETT, DODRIO, DODUO, DRAGONAIR, DRAGONITE, DROWZEE, DUGTRIO, EKANS,
	ELITE_ALAKAZAM, ELITE_ARBOK, ELITE_EXEGGUTOR, ELITE_HAUNTER, ELITE_ONIX, ELITE_RHYDON, EXEGGCUTE,
	FEAROW, GASTLY, GENGAR, GEODUDE, GLOOM, GOLBAT, GOLDEEN, GOLDUCK, GRAVELER, GROWLITHE, GYARADOS,
	HAUNTER, HITMONCHAN, HITMONLEE, HORSEA, HYPNO, JIGGLYPUFF, JYNX, KADABRA, KINGLER, KOFFING, LAPRAS,
	LICKITUNG, MACHAMP, MACHOKE, MACHOP, MAGNEMITE, MANKEY, MAROWAK, MEOWTH, MOLTRES, MRMIME, MUK,
	NIDOKING, NIDORINO, NINETALES, ODDISH, ONIX, PARASECT, PIDGEOT, PIDGEOTTO, PIDGEY, PIKACHU, POLIWAG,
	PONYTA, PSYDUCK, RAICHU, RAPIDASH, RATICATE, RATTATA, RHYDON, RHYHORN, SANDSHREW, SEEL, SHELLDER,
	SLOWBRO, SLOWPOKE, SNORLAX, SPEAROW, STARMIE, STARYU, TANGELA, TAUROS, TENTACOOL, TENTACRUEL,
	VENONAT, VENOMOTH, VENASAUR, VICTREEBELL, VILEPLUME, VOLTORB, VULPIX, WEEDLE, WEEPINBELL, WEEZING, ZAPDOS,
	ZUBAT
}
